version: 2.1

executors:
  leiningen:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.3
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    working_directory: /home/circleci/datahike-jdbc

jobs:
  setup:
    executor: leiningen
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}
            - source-
      - checkout
      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
      - restore_cache:
          keys:
            - deps-{{ checksum "project.clj" }}
            - deps-
      - run: lein deps
      - save_cache:
          key: deps-{{ checksum "project.clj" }}
          paths:
            - /home/circleci/.m2
            - /home/circleci/.lein
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - .m2
            - datahike-jdbc
            - bin

  integrationtest:
    executor: leiningen
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.3
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: alice
          POSTGRES_PASSWORD: foo
          POSTGRES_DB: config-test
      - image: circleci/mariadb:10.4
        environment:
          MYSQL_USER: alice
          MYSQL_PASSWORD: foo
          MYSQL_DATABASE: config-test
          MYSQL_RANDOM_ROOT_PASSWORD: true
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Run Integrationtests
          command: lein test
          no_output_timeout: 5m

  build:
    executor: leiningen
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Build
          command: lein uberjar
          no_output_timeout: 5m

  deploy-snapshot:
    executor: leiningen
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          command: |
            VERSION=$(head -n 1 project.clj | awk '{print $3}' | tr -d \")
            if [[ ${VERSION} =~ .*-SNAPSHOT ]]; then
                lein deploy clojars
            else
                exit 0
            fi
  deploy-release:
    executor: leiningen
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Deploy Release to Clojars
          command: |
            VERSION=$(head -n 1 project.clj | awk '{print $3}' | tr -d \")
            if [[ ${VERSION} =~ .*-SNAPSHOT ]]; then
                exit 0
            else
                lein deploy clojars
            fi

workflows:
  build_and_test:
    jobs:
      - setup
      - integrationtest:
          requires:
            - setup
      - build:
          requires:
            - setup
      - deploy-snapshot:
          filters:
            branches:
              only: development
          requires:
            - setup
            - integrationtest
            - build
      - deploy-release:
          filters:
            branches:
              only: master
          requires:
            - setup
            - integrationtest
            - build
